name: intl_phone_selector
description: "A highly customizable international phone number input package for Flutter with advanced validation, error handling, and multiple input styles."
version: 0.1.0
homepage: https://github.com/Syed-Bipul-Rahman/intl_phone_selector

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0



flutter:

