import 'country.dart';

class CountriesData {
  static List<Country> allCountries = [
    Country(
      name: 'Afghanistan',
      code: 'AF',
      dialCode: '+93',
      flagEmoji: '🇦🇫',
    ),
    Country(name: 'Albania', code: 'AL', dialCode: '+355', flagEmoji: '🇦🇱'),
    Country(name: 'Algeria', code: 'DZ', dialCode: '+213', flagEmoji: '🇩🇿'),
    Country(name: 'Andorra', code: 'AD', dialCode: '+376', flagEmoji: '🇦🇩'),
    Country(name: 'Angola', code: 'AO', dialCode: '+244', flagEmoji: '🇦🇴'),
    Country(
      name: 'Antigua and Barbuda',
      code: 'AG',
      dialCode: '+1-268',
      flagEmoji: '🇦🇬',
    ),
    Country(name: 'Argentina', code: 'AR', dialCode: '+54', flagEmoji: '🇦🇷'),
    Country(name: 'Armenia', code: 'AM', dialCode: '+374', flagEmoji: '🇦🇲'),
    Country(name: 'Australia', code: 'AU', dialCode: '+61', flagEmoji: '🇦🇺'),
    Country(name: 'Austria', code: 'AT', dialCode: '+43', flagEmoji: '🇦🇹'),
    Country(
      name: 'Azerbaijan',
      code: 'AZ',
      dialCode: '+994',
      flagEmoji: '🇦🇿',
    ),
    Country(name: 'Bahamas', code: 'BS', dialCode: '+1-242', flagEmoji: '🇧🇸'),
    Country(name: 'Bahrain', code: 'BH', dialCode: '+973', flagEmoji: '🇧🇭'),
    Country(
      name: 'Bangladesh',
      code: 'BD',
      dialCode: '+880',
      flagEmoji: '🇧🇩',
    ),
    Country(
      name: 'Barbados',
      code: 'BB',
      dialCode: '+1-246',
      flagEmoji: '🇧🇧',
    ),
    Country(name: 'Belarus', code: 'BY', dialCode: '+375', flagEmoji: '🇧🇾'),
    Country(name: 'Belgium', code: 'BE', dialCode: '+32', flagEmoji: '🇧🇪'),
    Country(name: 'Belize', code: 'BZ', dialCode: '+501', flagEmoji: '🇧🇿'),
    Country(name: 'Benin', code: 'BJ', dialCode: '+229', flagEmoji: '🇧🇯'),
    Country(name: 'Bhutan', code: 'BT', dialCode: '+975', flagEmoji: '🇧🇹'),
    Country(name: 'Bolivia', code: 'BO', dialCode: '+591', flagEmoji: '🇧🇴'),
    Country(
      name: 'Bosnia and Herzegovina',
      code: 'BA',
      dialCode: '+387',
      flagEmoji: '🇧🇦',
    ),
    Country(name: 'Botswana', code: 'BW', dialCode: '+267', flagEmoji: '🇧🇼'),
    Country(name: 'Brazil', code: 'BR', dialCode: '+55', flagEmoji: '🇧🇷'),
    Country(name: 'Brunei', code: 'BN', dialCode: '+673', flagEmoji: '🇧🇳'),
    Country(name: 'Bulgaria', code: 'BG', dialCode: '+359', flagEmoji: '🇧🇬'),
    Country(
      name: 'Burkina Faso',
      code: 'BF',
      dialCode: '+226',
      flagEmoji: '🇧🇫',
    ),
    Country(name: 'Burundi', code: 'BI', dialCode: '+257', flagEmoji: '🇧🇮'),
    Country(name: 'Cambodia', code: 'KH', dialCode: '+855', flagEmoji: '🇰🇭'),
    Country(name: 'Cameroon', code: 'CM', dialCode: '+237', flagEmoji: '🇨🇲'),
    Country(name: 'Canada', code: 'CA', dialCode: '+1', flagEmoji: '🇨🇦'),
    Country(
      name: 'Cape Verde',
      code: 'CV',
      dialCode: '+238',
      flagEmoji: '🇨🇻',
    ),
    Country(
      name: 'Central African Republic',
      code: 'CF',
      dialCode: '+236',
      flagEmoji: '🇨🇫',
    ),
    Country(name: 'Chad', code: 'TD', dialCode: '+235', flagEmoji: '🇹🇩'),
    Country(name: 'Chile', code: 'CL', dialCode: '+56', flagEmoji: '🇨🇱'),
    Country(name: 'China', code: 'CN', dialCode: '+86', flagEmoji: '🇨🇳'),
    Country(name: 'Colombia', code: 'CO', dialCode: '+57', flagEmoji: '🇨🇴'),
    Country(name: 'Comoros', code: 'KM', dialCode: '+269', flagEmoji: '🇰🇲'),
    Country(name: 'Congo', code: 'CG', dialCode: '+242', flagEmoji: '🇨🇬'),
    Country(
      name: 'Costa Rica',
      code: 'CR',
      dialCode: '+506',
      flagEmoji: '🇨🇷',
    ),
    Country(name: 'Croatia', code: 'HR', dialCode: '+385', flagEmoji: '🇭🇷'),
    Country(name: 'Cuba', code: 'CU', dialCode: '+53', flagEmoji: '🇨🇺'),
    Country(name: 'Cyprus', code: 'CY', dialCode: '+357', flagEmoji: '🇨🇾'),
    Country(
      name: 'Czech Republic',
      code: 'CZ',
      dialCode: '+420',
      flagEmoji: '🇨🇿',
    ),
    Country(
      name: 'Democratic Republic of the Congo',
      code: 'CD',
      dialCode: '+243',
      flagEmoji: '🇨🇩',
    ),
    Country(name: 'Denmark', code: 'DK', dialCode: '+45', flagEmoji: '🇩🇰'),
    Country(name: 'Djibouti', code: 'DJ', dialCode: '+253', flagEmoji: '🇩🇯'),
    Country(
      name: 'Dominica',
      code: 'DM',
      dialCode: '+1-767',
      flagEmoji: '🇩🇲',
    ),
    Country(
      name: 'Dominican Republic',
      code: 'DO',
      dialCode: '+1-809',
      flagEmoji: '🇩🇴',
    ),
    Country(name: 'Ecuador', code: 'EC', dialCode: '+593', flagEmoji: '🇪🇨'),
    Country(name: 'Egypt', code: 'EG', dialCode: '+20', flagEmoji: '🇪🇬'),
    Country(
      name: 'El Salvador',
      code: 'SV',
      dialCode: '+503',
      flagEmoji: '🇸🇻',
    ),
    Country(
      name: 'Equatorial Guinea',
      code: 'GQ',
      dialCode: '+240',
      flagEmoji: '🇬🇶',
    ),
    Country(name: 'Eritrea', code: 'ER', dialCode: '+291', flagEmoji: '🇪🇷'),
    Country(name: 'Estonia', code: 'EE', dialCode: '+372', flagEmoji: '🇪🇪'),
    Country(name: 'Eswatini', code: 'SZ', dialCode: '+268', flagEmoji: '🇸🇿'),
    Country(name: 'Ethiopia', code: 'ET', dialCode: '+251', flagEmoji: '🇪🇹'),
    Country(name: 'Fiji', code: 'FJ', dialCode: '+679', flagEmoji: '🇫🇯'),
    Country(name: 'Finland', code: 'FI', dialCode: '+358', flagEmoji: '🇫🇮'),
    Country(name: 'France', code: 'FR', dialCode: '+33', flagEmoji: '🇫🇷'),
    Country(name: 'Gabon', code: 'GA', dialCode: '+241', flagEmoji: '🇬🇦'),
    Country(name: 'Gambia', code: 'GM', dialCode: '+220', flagEmoji: '🇬🇲'),
    Country(name: 'Georgia', code: 'GE', dialCode: '+995', flagEmoji: '🇬🇪'),
    Country(name: 'Germany', code: 'DE', dialCode: '+49', flagEmoji: '🇩🇪'),
    Country(name: 'Ghana', code: 'GH', dialCode: '+233', flagEmoji: '🇬🇭'),
    Country(name: 'Greece', code: 'GR', dialCode: '+30', flagEmoji: '🇬🇷'),
    Country(name: 'Grenada', code: 'GD', dialCode: '+1-473', flagEmoji: '🇬🇩'),
    Country(name: 'Guatemala', code: 'GT', dialCode: '+502', flagEmoji: '🇬🇹'),
    Country(name: 'Guinea', code: 'GN', dialCode: '+224', flagEmoji: '🇬🇳'),
    Country(
      name: 'Guinea-Bissau',
      code: 'GW',
      dialCode: '+245',
      flagEmoji: '🇬🇼',
    ),
    Country(name: 'Guyana', code: 'GY', dialCode: '+592', flagEmoji: '🇬🇾'),
    Country(name: 'Haiti', code: 'HT', dialCode: '+509', flagEmoji: '🇭🇹'),
    Country(name: 'Honduras', code: 'HN', dialCode: '+504', flagEmoji: '🇭🇳'),
    Country(name: 'Hungary', code: 'HU', dialCode: '+36', flagEmoji: '🇭🇺'),
    Country(name: 'Iceland', code: 'IS', dialCode: '+354', flagEmoji: '🇮🇸'),
    // Country(name: 'India', code: 'IN', dialCode: '+91', flagEmoji: '🇮🇳'),
    Country(name: 'Indonesia', code: 'ID', dialCode: '+62', flagEmoji: '🇮🇩'),
    Country(name: 'Iran', code: 'IR', dialCode: '+98', flagEmoji: '🇮🇷'),
    Country(name: 'Iraq', code: 'IQ', dialCode: '+964', flagEmoji: '🇮🇶'),
    Country(name: 'Ireland', code: 'IE', dialCode: '+353', flagEmoji: '🇮🇪'),
    // Country(name: 'Israel', code: 'IL', dialCode: '+972', flagEmoji: '🇮🇱'),
    Country(name: 'Italy', code: 'IT', dialCode: '+39', flagEmoji: '🇮🇹'),
    Country(name: 'Jamaica', code: 'JM', dialCode: '+1-876', flagEmoji: '🇯🇲'),
    Country(name: 'Japan', code: 'JP', dialCode: '+81', flagEmoji: '🇯🇵'),
    Country(name: 'Jordan', code: 'JO', dialCode: '+962', flagEmoji: '🇯🇴'),
    Country(name: 'Kazakhstan', code: 'KZ', dialCode: '+7', flagEmoji: '🇰🇿'),
    Country(name: 'Kenya', code: 'KE', dialCode: '+254', flagEmoji: '🇰🇪'),
    Country(name: 'Kiribati', code: 'KI', dialCode: '+686', flagEmoji: '🇰🇮'),
    Country(name: 'Kuwait', code: 'KW', dialCode: '+965', flagEmoji: '🇰🇼'),
    Country(
      name: 'Kyrgyzstan',
      code: 'KG',
      dialCode: '+996',
      flagEmoji: '🇰🇬',
    ),
    Country(name: 'Laos', code: 'LA', dialCode: '+856', flagEmoji: '🇱🇦'),
    Country(name: 'Latvia', code: 'LV', dialCode: '+371', flagEmoji: '🇱🇻'),
    Country(name: 'Lebanon', code: 'LB', dialCode: '+961', flagEmoji: '🇱🇧'),
    Country(name: 'Lesotho', code: 'LS', dialCode: '+266', flagEmoji: '🇱🇸'),
    Country(name: 'Liberia', code: 'LR', dialCode: '+231', flagEmoji: '🇱🇷'),
    Country(name: 'Libya', code: 'LY', dialCode: '+218', flagEmoji: '🇱🇾'),
    Country(
      name: 'Liechtenstein',
      code: 'LI',
      dialCode: '+423',
      flagEmoji: '🇱🇮',
    ),
    Country(name: 'Lithuania', code: 'LT', dialCode: '+370', flagEmoji: '🇱🇹'),
    Country(
      name: 'Luxembourg',
      code: 'LU',
      dialCode: '+352',
      flagEmoji: '🇱🇺',
    ),
    Country(
      name: 'Madagascar',
      code: 'MG',
      dialCode: '+261',
      flagEmoji: '🇲🇬',
    ),
    Country(name: 'Malawi', code: 'MW', dialCode: '+265', flagEmoji: '🇲🇼'),
    Country(name: 'Malaysia', code: 'MY', dialCode: '+60', flagEmoji: '🇲🇾'),
    Country(name: 'Maldives', code: 'MV', dialCode: '+960', flagEmoji: '🇲🇻'),
    Country(name: 'Mali', code: 'ML', dialCode: '+223', flagEmoji: '🇲🇱'),
    Country(name: 'Malta', code: 'MT', dialCode: '+356', flagEmoji: '🇲🇹'),
    Country(
      name: 'Marshall Islands',
      code: 'MH',
      dialCode: '+692',
      flagEmoji: '🇲🇭',
    ),
    Country(
      name: 'Mauritania',
      code: 'MR',
      dialCode: '+222',
      flagEmoji: '🇲🇷',
    ),
    Country(name: 'Mauritius', code: 'MU', dialCode: '+230', flagEmoji: '🇲🇺'),
    Country(name: 'Mexico', code: 'MX', dialCode: '+52', flagEmoji: '🇲🇽'),
    Country(
      name: 'Micronesia',
      code: 'FM',
      dialCode: '+691',
      flagEmoji: '🇫🇲',
    ),
    Country(name: 'Moldova', code: 'MD', dialCode: '+373', flagEmoji: '🇲🇩'),
    Country(name: 'Monaco', code: 'MC', dialCode: '+377', flagEmoji: '🇲🇨'),
    Country(name: 'Mongolia', code: 'MN', dialCode: '+976', flagEmoji: '🇲🇳'),
    Country(
      name: 'Montenegro',
      code: 'ME',
      dialCode: '+382',
      flagEmoji: '🇲🇪',
    ),
    Country(name: 'Morocco', code: 'MA', dialCode: '+212', flagEmoji: '🇲🇦'),
    Country(
      name: 'Mozambique',
      code: 'MZ',
      dialCode: '+258',
      flagEmoji: '🇲🇿',
    ),
    Country(name: 'Myanmar', code: 'MM', dialCode: '+95', flagEmoji: '🇲🇲'),
    Country(name: 'Namibia', code: 'NA', dialCode: '+264', flagEmoji: '🇳🇦'),
    Country(name: 'Nauru', code: 'NR', dialCode: '+674', flagEmoji: '🇳🇷'),
    Country(name: 'Nepal', code: 'NP', dialCode: '+977', flagEmoji: '🇳🇵'),
    Country(
      name: 'Netherlands',
      code: 'NL',
      dialCode: '+31',
      flagEmoji: '🇳🇱',
    ),
    Country(
      name: 'New Zealand',
      code: 'NZ',
      dialCode: '+64',
      flagEmoji: '🇳🇿',
    ),
    Country(name: 'Nicaragua', code: 'NI', dialCode: '+505', flagEmoji: '🇳🇮'),
    Country(name: 'Niger', code: 'NE', dialCode: '+227', flagEmoji: '🇳🇪'),
    Country(name: 'Nigeria', code: 'NG', dialCode: '+234', flagEmoji: '🇳🇬'),
    Country(
      name: 'North Korea',
      code: 'KP',
      dialCode: '+850',
      flagEmoji: '🇰🇵',
    ),
    Country(
      name: 'North Macedonia',
      code: 'MK',
      dialCode: '+389',
      flagEmoji: '🇲🇰',
    ),
    Country(name: 'Norway', code: 'NO', dialCode: '+47', flagEmoji: '🇳🇴'),
    Country(name: 'Oman', code: 'OM', dialCode: '+968', flagEmoji: '🇴🇲'),
    Country(name: 'Pakistan', code: 'PK', dialCode: '+92', flagEmoji: '🇵🇰'),
    Country(name: 'Palau', code: 'PW', dialCode: '+680', flagEmoji: '🇵🇼'),
    Country(name: 'Palestine', code: 'PS', dialCode: '+970', flagEmoji: '🇵🇸'),
    Country(name: 'Panama', code: 'PA', dialCode: '+507', flagEmoji: '🇵🇦'),
    Country(
      name: 'Papua New Guinea',
      code: 'PG',
      dialCode: '+675',
      flagEmoji: '🇵🇬',
    ),
    Country(name: 'Paraguay', code: 'PY', dialCode: '+595', flagEmoji: '🇵🇾'),
    Country(name: 'Peru', code: 'PE', dialCode: '+51', flagEmoji: '🇵🇪'),
    Country(
      name: 'Philippines',
      code: 'PH',
      dialCode: '+63',
      flagEmoji: '🇵🇭',
    ),
    Country(name: 'Poland', code: 'PL', dialCode: '+48', flagEmoji: '🇵🇱'),
    Country(name: 'Portugal', code: 'PT', dialCode: '+351', flagEmoji: '🇵🇹'),
    Country(name: 'Qatar', code: 'QA', dialCode: '+974', flagEmoji: '🇶🇦'),
    Country(name: 'Romania', code: 'RO', dialCode: '+40', flagEmoji: '🇷🇴'),
    Country(name: 'Russia', code: 'RU', dialCode: '+7', flagEmoji: '🇷🇺'),
    Country(name: 'Rwanda', code: 'RW', dialCode: '+250', flagEmoji: '🇷🇼'),
    Country(
      name: 'Saint Kitts and Nevis',
      code: 'KN',
      dialCode: '+1-869',
      flagEmoji: '🇰🇳',
    ),
    Country(
      name: 'Saint Lucia',
      code: 'LC',
      dialCode: '+1-758',
      flagEmoji: '🇱🇨',
    ),
    Country(
      name: 'Saint Vincent and the Grenadines',
      code: 'VC',
      dialCode: '+1-784',
      flagEmoji: '🇻🇨',
    ),
    Country(name: 'Samoa', code: 'WS', dialCode: '+685', flagEmoji: '🇼🇸'),
    Country(
      name: 'San Marino',
      code: 'SM',
      dialCode: '+378',
      flagEmoji: '🇸🇲',
    ),
    Country(
      name: 'Sao Tome and Principe',
      code: 'ST',
      dialCode: '+239',
      flagEmoji: '🇸🇹',
    ),
    Country(
      name: 'Saudi Arabia',
      code: 'SA',
      dialCode: '+966',
      flagEmoji: '🇸🇦',
    ),
    Country(name: 'Senegal', code: 'SN', dialCode: '+221', flagEmoji: '🇸🇳'),
    Country(name: 'Serbia', code: 'RS', dialCode: '+381', flagEmoji: '🇷🇸'),
    Country(
      name: 'Seychelles',
      code: 'SC',
      dialCode: '+248',
      flagEmoji: '🇸🇨',
    ),
    Country(
      name: 'Sierra Leone',
      code: 'SL',
      dialCode: '+232',
      flagEmoji: '🇸🇱',
    ),
    Country(name: 'Singapore', code: 'SG', dialCode: '+65', flagEmoji: '🇸🇬'),
    Country(name: 'Slovakia', code: 'SK', dialCode: '+421', flagEmoji: '🇸🇰'),
    Country(name: 'Slovenia', code: 'SI', dialCode: '+386', flagEmoji: '🇸🇮'),
    Country(
      name: 'Solomon Islands',
      code: 'SB',
      dialCode: '+677',
      flagEmoji: '🇸🇧',
    ),
    Country(name: 'Somalia', code: 'SO', dialCode: '+252', flagEmoji: '🇸🇴'),
    Country(
      name: 'South Africa',
      code: 'ZA',
      dialCode: '+27',
      flagEmoji: '🇿🇦',
    ),
    Country(
      name: 'South Korea',
      code: 'KR',
      dialCode: '+82',
      flagEmoji: '🇰🇷',
    ),
    Country(
      name: 'South Sudan',
      code: 'SS',
      dialCode: '+211',
      flagEmoji: '🇸🇸',
    ),
    Country(name: 'Spain', code: 'ES', dialCode: '+34', flagEmoji: '🇪🇸'),
    Country(name: 'Sri Lanka', code: 'LK', dialCode: '+94', flagEmoji: '🇱🇰'),
    Country(name: 'Sudan', code: 'SD', dialCode: '+249', flagEmoji: '🇸🇩'),
    Country(name: 'Suriname', code: 'SR', dialCode: '+597', flagEmoji: '🇸🇷'),
    Country(name: 'Sweden', code: 'SE', dialCode: '+46', flagEmoji: '🇸🇪'),
    Country(
      name: 'Switzerland',
      code: 'CH',
      dialCode: '+41',
      flagEmoji: '🇨🇭',
    ),
    Country(name: 'Syria', code: 'SY', dialCode: '+963', flagEmoji: '🇸🇾'),
    Country(name: 'Taiwan', code: 'TW', dialCode: '+886', flagEmoji: '🇹🇼'),
    Country(
      name: 'Tajikistan',
      code: 'TJ',
      dialCode: '+992',
      flagEmoji: '🇹🇯',
    ),
    Country(name: 'Tanzania', code: 'TZ', dialCode: '+255', flagEmoji: '🇹🇿'),
    Country(name: 'Thailand', code: 'TH', dialCode: '+66', flagEmoji: '🇹🇭'),
    Country(
      name: 'Timor-Leste',
      code: 'TL',
      dialCode: '+670',
      flagEmoji: '🇹🇱',
    ),
    Country(name: 'Togo', code: 'TG', dialCode: '+228', flagEmoji: '🇹🇬'),
    Country(name: 'Tonga', code: 'TO', dialCode: '+676', flagEmoji: '🇹🇴'),
    Country(
      name: 'Trinidad and Tobago',
      code: 'TT',
      dialCode: '+1-868',
      flagEmoji: '🇹🇹',
    ),
    Country(name: 'Tunisia', code: 'TN', dialCode: '+216', flagEmoji: '🇹🇳'),
    Country(name: 'Turkey', code: 'TR', dialCode: '+90', flagEmoji: '🇹🇷'),
    Country(
      name: 'Turkmenistan',
      code: 'TM',
      dialCode: '+993',
      flagEmoji: '🇹🇲',
    ),
    Country(name: 'Tuvalu', code: 'TV', dialCode: '+688', flagEmoji: '🇹🇻'),
    Country(name: 'Uganda', code: 'UG', dialCode: '+256', flagEmoji: '🇺🇬'),
    Country(name: 'Ukraine', code: 'UA', dialCode: '+380', flagEmoji: '🇺🇦'),
    Country(
      name: 'United Arab Emirates',
      code: 'AE',
      dialCode: '+971',
      flagEmoji: '🇦🇪',
    ),
    Country(
      name: 'United Kingdom',
      code: 'GB',
      dialCode: '+44',
      flagEmoji: '🇬🇧',
    ),
    Country(
      name: 'United States',
      code: 'US',
      dialCode: '+1',
      flagEmoji: '🇺🇸',
    ),
    Country(name: 'Uruguay', code: 'UY', dialCode: '+598', flagEmoji: '🇺🇾'),
    Country(
      name: 'Uzbekistan',
      code: 'UZ',
      dialCode: '+998',
      flagEmoji: '🇺🇿',
    ),
    Country(name: 'Vanuatu', code: 'VU', dialCode: '+678', flagEmoji: '🇻🇺'),
    Country(name: 'Venezuela', code: 'VE', dialCode: '+58', flagEmoji: '🇻🇪'),
    Country(name: 'Vietnam', code: 'VN', dialCode: '+84', flagEmoji: '🇻🇳'),
    Country(name: 'Yemen', code: 'YE', dialCode: '+967', flagEmoji: '🇾🇪'),
    Country(name: 'Zambia', code: 'ZM', dialCode: '+260', flagEmoji: '🇿🇲'),
    Country(name: 'Zimbabwe', code: 'ZW', dialCode: '+263', flagEmoji: '🇿🇼'),
  ];

  static Country getCountryByCode(String code) {
    return allCountries.firstWhere(
      (country) => country.code == code,
      orElse: () => allCountries.first,
    );
  }

  static Country getCountryByDialCode(String dialCode) {
    return allCountries.firstWhere(
      (country) => country.dialCode == dialCode,
      orElse: () => allCountries.first,
    );
  }
}
